# Variables

@baseUrl = http://localhost:3333

# Health Check
GET {{baseUrl}}/health

###

# Get Rooms
GET {{baseUrl}}/rooms

###

# Create Room
POST {{baseUrl}}/rooms
Accept: application/json
Content-Type: application/json

{
  "name": "Sala de Teste",
  "description": "Isso é uma sala de teste"
}